# -*- coding: utf-8 -*-
"""flight_delay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGkXwInCdb9XktNcJUGmClG357VGATd9
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import zipfile

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

import warnings
warnings.filterwarnings('ignore')

zip_path = "files.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("flight_data")

print("Files Extracted Successfully")

flights = pd.read_csv("flight_data/flights.csv")
delay_causes = pd.read_csv("flight_data/delay_causes.csv")
ripple = pd.read_csv("flight_data/ripple_effects.csv")
airports = pd.read_csv("flight_data/airports.csv")
aircraft = pd.read_csv("flight_data/aircraft.csv")

print(flights.head())

flights.drop_duplicates(inplace=True)
delay_causes.drop_duplicates(inplace=True)

flights.fillna(0, inplace=True)
delay_causes.fillna(0, inplace=True)
aircraft.fillna(0, inplace=True)

print("Missing Values Removed")

df = flights.merge(
    delay_causes,
    on="flight_id",
    how="left"
)

df = df.merge(
    aircraft,
    on="tail_number",
    how="left"
)

print(df.shape)

df["delay_target"] = (
    df["dep_delay_min"] > 15
).astype(int)

df["scheduled_dep"] = pd.to_datetime(df["scheduled_dep"])

df["hour"] = df["scheduled_dep"].dt.hour
df["month"] = df["scheduled_dep"].dt.month
df["dayofweek"] = df["scheduled_dep"].dt.dayofweek

categorical_cols = [
    "carrier_code",
    "origin_iata",
    "dest_iata",
    "root_cause_category"
]

encoder = LabelEncoder()

for col in categorical_cols:
    if col in df.columns:
        df[col] = encoder.fit_transform(
            df[col].astype(str)
        )

features = ['flight_id', 'carrier_code_x', 'flight_number', 'origin_iata',
       'dest_iata', 'scheduled_dep', 'actual_dep', 'scheduled_arr',
       'actual_arr', 'dep_delay_min', 'arr_delay_min', 'flight_status',
       'tail_number', 'distance_km', 'is_cancelled', 'cancellation_code',
       'root_cause_category', 'carrier_delay_min', 'weather_delay_min',
       'nas_delay_min', 'security_delay_min', 'late_aircraft_delay_min',
       'weather_event_id', 'atc_ground_stop', 'ground_stop_airport',
       'maintenance_flag', 'maintenance_type', 'crew_issue_flag',
       'gate_conflict_flag', 'fueling_delay_min', 'catering_delay_min',
       'aircraft_type', 'carrier_code_y', 'age_years', 'seat_capacity',
       'engine_count', 'maintenance_score', 'last_heavy_check',
       'avg_daily_utilization_hr', 'rotation_hub', 'delay_target', 'hour',
       'month', 'dayofweek'
]

X = df[features]
y = df["delay_target"]

for col in df.columns:
    print(col)

print("Columns in dataset:")
print(df.columns)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X.dtypes)

string_cols = X.select_dtypes(include=['object']).columns
print(string_cols)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in string_cols:
    X[col] = le.fit_transform(X[col].astype(str))

if 'flight_id' in X.columns:
    X = X.drop('flight_id', axis=1)

print(X.dtypes)

print(X_train.select_dtypes(include=['object']).columns)

for col in X_train.select_dtypes(include=['object']).columns:
    print("\nColumn:", col)
    print(X_train[col].head())

X = X.drop(columns=['flight_id'], errors='ignore')

from sklearn.preprocessing import LabelEncoder

for col in X.columns:
    if X[col].dtype == 'object':
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col].astype(str))

print(X.dtypes)

print(X.columns)

X = X.drop(columns=['scheduled_dep'], errors='ignore')

datetime_cols = X.select_dtypes(include=['datetime64[ns]']).columns

print("Datetime Columns:", datetime_cols)

X = X.drop(columns=datetime_cols)

print(X.dtypes)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model.fit(X_train, y_train)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Trained Successfully")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", round(accuracy*100,2), "%")

print(classification_report(y_test, y_pred))

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

import joblib

joblib.dump(
    model,
    "flight_delay_model.pkl"
)

print("Model Saved")

from google.colab import files

files.download(
    "flight_delay_model.pkl"
)