# -*- coding: utf-8 -*-
"""flight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RM3m3ZmdYigGS7XOp1Yjk7LzIa8Aazct
"""

import os
os.environ['KAGGLE_USERNAME']='anasakn'
os.environ['KAGGLE_KEY']='KGAT_5ff2b32969c431e336640881309e4b2c'

!pip install kaggle

!kaggle datasets download -d 'gauranshmehra3c24/flight-dataset'

!unzip flight-dataset.zip

import pandas as pd
df = pd.read_csv("flight-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))
print(df.shape)

df.info()

df.duplicated().sum()

df.dtypes

df.columns

df.isnull().sum()

print(df['TransactionTime'].dtype)

print(df['TransactionTime'].head())

import pandas as pd

df['TransactionTime'] = pd.to_numeric(df['TransactionTime'], errors='coerce')

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.boxplot(df['TransactionAmount'])
plt.title('Outlier Detection using Boxplot (TransactionAmount)')
plt.ylabel('Transaction Amount')
plt.show()

plt.scatter(df.index, df['TransactionAmount'])
plt.title('scatter plot (TransactionAmount)')
plt.xlabel('index')
plt.ylabel('TransactionAmount')
plt.show()

import pandas as pd
import zipfile
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Load dataset from ZIP
with zipfile.ZipFile('archive (1).zip', 'r') as zip_ref:
    df = pd.read_csv(zip_ref.open('flight_delay_prediction.csv'))

# Convert TransactionTime to datetime
df['TransactionTime'] = pd.to_datetime(df['TransactionTime'])

# Extract useful features
df['Hour'] = df['TransactionTime'].dt.hour
df['Day'] = df['TransactionTime'].dt.day
df['Month'] = df['TransactionTime'].dt.month

# Encode categorical columns
le_merchant = LabelEncoder()
le_category = LabelEncoder()

df['Merchant'] = le_merchant.fit_transform(df['Merchant'])
df['Category'] = le_category.fit_transform(df['Category'])

# Features and target
X = df[['Merchant', 'Category', 'Hour', 'Day', 'Month', 'IsFraud']]
y = df['TransactionAmount']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("R² Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# Sample predictions
results = pd.DataFrame({
    'Actual': y_test.values[:10],
    'Predicted': y_pred[:10]
})

print(results)