# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FzJFwhvzLr2CF9Aat16OjNEKzQAYzc0
"""

import os
os.environ['KAGGLE_USERNAME']='anasakn'
os.environ['KAGGLE_KEY']='KGAT_add5ce6c99a0e8e86625de24897997a5'

!pip install kaggle

!kaggle datasets download -d 'paramvir705/netflix-dataset'

!unzip netflix-dataset.zip

import pandas as pd
df = pd.read_csv("netflix-dataset.zip")
df.head(10)

print(len(df))
print(df.shape)

df.info()

df.duplicated().sum()

df.dtypes

df.columns

df.drop

df.isnull().sum()

df.tail(10)

df.describe()

df['show_id'].fillna(df['show_id'], inplace = True)
print(df[['show_id']].head(10))
print(df[['show_id']].isnull().sum())

df.drop_duplicates(inplace=True)
print(df)

df.drop('description', axis=1, inplace=True)
print(df.columns)

df['director']=df['director'].fillna('unknown')

df['cast']=df['cast'].fillna('unknown')

df['country']=df['country'].fillna('unknown')

df['date_added']=df['date_added'].fillna('unknown')

df['rating']=df['rating'].fillna('unknown')

df['duration']=df['duration'].fillna('unknown')

df.isnull().sum()

import matplotlib.pyplot as plt
plt.boxplot(df['release_year'])
plt.title('outlier Detection using Boxplot(release_year)')
plt.ylabel('release_year')
plt.show()

plt.scatter(df.index, df['release_year'])
plt.title('scatter plot (release_year)')
plt.xlabel('index')
plt.ylabel('release_year')
plt.show()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
df = pd.read_csv("/content/netflix_titles.csv")
df = df.drop(['show_id', 'title', 'director', 'cast',
              'country', 'date_added', 'description'],
             axis=1, errors='ignore')
df = df.fillna("Unknown")
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])
y = df['release_year']
X = df.drop('release_year', axis=1)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, pred))
print("MSE:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))
print("Model trained successfully")