# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kb3wuMp6Cptlc1Rw2fKH7jxOIAucClXo
"""

import os
os.environ['KAGGLE_USERNAME']='anasakn'
os.environ['KAGGLE_KEY']='KGAT_babd84870aae64bc151c232b39104be1'

!pip install kaggle

!kaggle datasets download -d 'yasserh/titanic-dataset'

!unzip titanic-dataset.zip

import pandas as pd
df = pd.read_csv("titanic-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))
print(df.shape)

df.duplicated().sum()

df.dtypes

df.info

df.describe()

df.columns

df.drop

df['Sex']=df['Sex'].map({0:"Male",1:"Female"})

df = df.drop(['Name', 'Ticket', 'Cabin'], axis=1, errors='ignore')

print(df.columns)

df['Sex'] = df['Sex'].astype('category').cat.codes
df['Age'] = df['Age'].fillna(df['Age'].median())
df = df.fillna(df.median(numeric_only=True))
print(df.isnull().sum())

df['Sex'] = df['Sex'].astype('category').cat.codes
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df = df.fillna(df.median(numeric_only=True))

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

df['Sex']=df['Sex'].fillna('unknown')

df.isnull().sum()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Load dataset
df = pd.read_csv("Titanic-Dataset.csv")

# Handle missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Convert categorical data to numeric
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

# Select features
X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

# Target variable
y = df['Survived']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("R² Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# Show sample predictions
results = pd.DataFrame({
    'Actual': y_test.values[:10],
    'Predicted': y_pred[:10]
})

print("\nSample Predictions:")
print(results)