# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1px8ptOiBzUNDTqMktlGvnHq6yzDKWoQE
"""

n1=int(input())
n2=int(input())
if(n1>n2):
  print("n1 is largest")
else:
  print("n2 is largest")

for i in range(4):
    for j in range(5):
        print(i, j)

a=input()
if(a==a[::-1]):
  print("palindrome")
else:
  print("not palindrome")

n=int(input())
fact=1
for i in range (1,n+1):
 fact*=i
 print("Factorial is:",fact)

a=int(input())
length=len(str(a))
s=0
t=a
while(t>0):
 d=t%10
 s+=d**length
 t=t//10
 if(s==a):
  print("Armstrong")
 else:
  print("Not Armstrong")

for num in range(1,51):
  if(num>1):
    for i in range(2,num):
      if num % i == 0:
        break
      else:
        print(num)

c=float(input())
f=(c*9/5)+32
print(f)

n=int(input())
a,b=0,1
for i in range(n):
 print(a)
 a,b = b,a+b

a=input()
b=input()
a,b = b,a
print(a)
print(b)

a=int(input())
b=int(input())
c=int(input())
avg=(a+b+c)/3
print(avg)

n = input()
vowels ="aeiou"
count=0
for ch in n:
  if ch in vowels:
    print(ch)
    count+=1
print(count)

a=int(input())
b=int(input())
x=a
y=b
while b!=0:
  a,b = b,a%b

  gcd = a

  lcm=(x * y) // gcd
  print("GCD =",gcd)
  print("LCM =",lcm)

num = [3,17,29,7,65,92]
largest=max(num)
smallest=min(num)
print(largest)
print(smallest)

a=int(input())
b=int(input())
print("Add=",a+b)
print("Sub=",a-b)
print("Mul=",a*b)
print("div=",a%b)

a=int(input())
if a>0:
  print("positive")
elif a<0:
  print("negative")
else:
  print("zero")

x=int(input())
if x%4 == 0:
  print("leapyear")
else:
  print("not leapyear")

x=int(input())
if x%2 == 0:
  print("EVEN")
else:
  print("ODD")

s1=input()
s2=input()
if sorted (s1)==sorted (s2):
  print("Annagram")
else:
  print("Not Annagram")



for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="")
  print()

n=int(input())
for i in range(n):
  print (" "*i+"*"*(n-i))

n=int(input())
for i in range(1,n+1):
  print (" " * (n - i) + "* " * i)
for i in range(n-1,0,-1):
  print (" " * (n - i) + "* " * i)

n=int(input())
for i in range(1,n+1):
  print (" " * (n - i) + "* " * i)

s1=input()
s2=input()
if (s1==s2,s2==s1):
  print("Annagram")
else:
  print("Not Annagram")

s1=input()
s2=input()
if (len(s1)!= len(s2)):
  print("not Annagram")
elif sorted(a) ==sorted(b):
  print("Annagram")
else:
  print("not Annagram")

a=[20,40,50,10,30]
largest = sorted(a,reverse = True)[:3]
print(largest)

import math
a=int(input())
if math.sqrt(a):
  print("power of 2")
else:
  print("not")

text = input()
s= text[3:13]
print(s)

s = input()

l = ""

for i in range(len(s)):
    cur = ""

    for j in range(i, len(s)):
        if s[j] not in cur:
            cur += s[j]
        else:
            break

    if len(cur) > len(l):
        l = cur

print(len(l))

s1 = input()
s2 = input()

count = 0
i = 0

try:
    while True:
        if s1[i] != s2[i]:
            count += 1
        i += 1

except:
    pass

if count == 1:
    print("yes")
else:
    print("no")

n = int(input())
x = list(map(int, input().split()))

for i in range(n):
  if x[i] == 0:
        d = x[i - 1] + 1
        print(d)
        break

#class & object
class student:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def display(self):
    print("Name:",self.name)
    print("Aga:",self.age)
obj = student("HEMS",3)
obj.display()

#inheritance
class father:
  def bike(self):
    print("father has bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj = son()
obj.bike()

#polymorphism(method overiding)
class Animal:
  def sound(self):
    print("animal make sound")
class Dog(Animal):
  def barks(self):
    print("dog barks")
obj = Dog()
obj.sound()

#abstraction
class bank:
  def __init__(self):
    self.__balance=5000
  def show_balance(self):
    print("balance",self.__balance)
obj = bank()
obj.show_balance()

#polymorphism(overloading)
class multiply:
  def product(self, a=None, b=None, c=None):
    if a and b and c:
      print("product=",a*b*c)
    elif a and b:
      print("product=",a*b)
    else :
      print("invalid input")
obj = multiply()
obj.product(2,3)
obj.product(2,3,4)

n=int(input())
S=str(n)
rev=s[::-1]
if(n>1):
  for i in range(2,n):
   if(n%i==0 and int(rev)%i==0):
    print("not prime")
    break
  else:
    print("prime")
else:
  print("not prime")

n=int(input())
a=0
for i in range(1,n+1):
  if(i%2==0):
    a=-i
  else:
    a=i
  print(a)

n=int(input())
s1=str(n)
r1=s1[::-1]
sq1=n**2
sq2=int(r1)**2
s2=str(sq2)
r2=s2[::-1]
if(sq1 == int(r2)):
 print("adam number")
else:
  print("not")

for _ in range(int(input())):
    n, k = map(int, input().split())
    a = list(input().split())
    count = 0
    for i in range(n):
        a[i] = int(a[i]) + k
        if (a[i] % 7 == 0):
            count += 1
    print(count)

for _ in range(int(input())):
    n,m = map(int,input().split())
    a = set(map(int,input().split()))
    b = set(map(int,input().split()))

    common = a.intersection(b)
    print(len(common))

k, n = map(int,input().split())
l = []
for j in range(k):
    l.append(input())
for s in range(n):
    t = input()
    if len(t) >= 47:
        print('Good')
        continue
    for j in l:
         if j in t:
             print('Good')
             break
    else:
          print('Bad')

student_name = input()
m1, m2, m3, m4 = map(int, input().split())
total = m1 + m2 + m3 + m4
avg = (m1 + m2 + m3 + m4)/4
highest = max(m1, m2, m3, m4)
print("Total", total)
print("Average", avg)
print("Highest Mark",highest )
if total < 350:
  print("status:Fail")
else:
  print("status:Pass")

Employee_name = input()
s1, s2, s3, s4, s5 = map(int, input().split())
avg = (s1 + s2 + s3 + s4 + s5)/4
highest = max(s1, s2, s3, s4, s5)
print("Average score", avg)
print("Best Score",highest)
count = 0
for i in s1,s2,s3,s4,s5:
 if i > 80:
   count+=1
print("Months Above 80:",count)

#University Attendance Management System
s1, s2, s3, s4, s5, s6 = map(int, input().split())
Attendance = s1, s2, s3, s4, s5, s6
highest = max(Attendance)
lowest = min(Attendance)
print("Highest Attendance:",highest)
print("lowest Attendance:",lowest)
count=0
for i in Attendance:
  if i > 75:
     count+=1
print("Eligible Students",count)

#Cricket Team Statistics
player_name = input()
s1, s2, s3, s4, s5 = map(int, input().split())
avg = (s1 + s2 + s3 + s4 + s5)/5
highest = max(s1, s2, s3, s4, s5)
lowest = min(s1, s2, s3, s4, s5)
print("Highest score",highest )
print("Lowest score",lowest )
print("Average score", avg)
count = 0
for i in s1,s2,s3,s4,s5:
 if i > 50:
   count+=1
print("Half Centuries:",count)

#E-Commerce Shopping Cart
Prices=[1200, 3500, 800, 1500]
total=sum(Prices)
print("Total Bill:",total)
print("Costliest Item:",max(Prices))
if  total > 5000:
  discount=total*15/100
print("Discounted Bill:",total-discount)

#Hospital Patient Monitoring System
Patient="Kumar"
Temperatures=[98.4, 99.1, 101.2, 102.3, 98.9]
highest = max(Temperatures)
lowest = min(Temperatures)
print("Highest Temperatures:",highest)
print("lowest Temperatures:",lowest)
count=0
for i in Temperatures:
  if i > 100:
     count+=1
print("Abnormal Readings:",count)

from collections import Counter
a=input().split()
b=input().split()
if Counter(a) == Counter(b):
   print("equivalent log")
else:
   print("Different log")

Booked_Seats=[1, 3, 5, 7, 10, 15]
total=sum(Booked_Seats)
print("Total Booked Seats: ",total)

line1 = input().split()
line2 = input().split()
freq1={}
freq2={}
for word in line1:
  freq1[word]=freq1.get(word,0)+1
for word in line2:
  freq2[word]=freq2.get(word,0)+1
if freq1 == freq2:
  print("equivalent")
else:
  print("not equivalent")

# 1
l=list(map(int,input().split()))
first = second = -1
for i in l:
  if (i > first):
    second = first
    first = i
  elif(i>second):
    second = i
print(second)

# 2
s = input()

for ch in s:
    if s.count(ch) == 1:
        print(ch)
        break

# 4
number = list(map(int,input().split()))
odd=[]
even=[]
for num in number:
  if num%2!= 0:
    odd.append(num)
  else:
    even.append(num)
rearrange_number= even+odd
print(rearrange_number)

# 3
a = list(input())
k=2
result = a[-k:] + a[:-k]
print(result)

# 8
s=input()
vowels = ""

# 7
arr = [2, 7, 11, 15, 3, 6]
t = 9

for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] + arr[j] == t:
            print((arr[i], arr[j]))

#5
def total(lst):
  s=0
  for i in lst:
    if isinstance(i,list):
      s += total(i)
    else:
      s+=i
  return s
print(total([1,[2,3],[4,[5,6]]]))

#6
for i in range(1, 101):
    n = str(i)

    if len(n) == 1:
        print(i, end=" ")
    else:
        if int(n[0]) + int(n[1]) == int(n[0]) * int(n[1]):
            print(i, end=" ")

import os
os.environ['KAGGLE_USERNAME']='ANAS.AKN'
os.environ['KAGGLE_KEY']='KGAT_babd84870aae64bc151c232b39104be1'

!pip install kaggle

