# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1px8ptOiBzUNDTqMktlGvnHq6yzDKWoQE
"""

n1=int(input())
n2=int(input())
if(n1>n2):
  print("n1 is largest")
else:
  print("n2 is largest")

for i in range(4):
    for j in range(5):
        print(i, j)

a=input()
if(a==a[::-1]):
  print("palindrome")
else:
  print("not palindrome")

n=int(input())
fact=1
for i in range (1,n+1):
 fact*=i
 print("Factorial is:",fact)

a=int(input())
length=len(str(a))
s=0
t=a
while(t>0):
 d=t%10
 s+=d**length
 t=t//10
 if(s==a):
  print("Armstrong")
 else:
  print("Not Armstrong")

for num in range(1,51):
  if(num>1):
    for i in range(2,num):
      if num % i == 0:
        break
      else:
        print(num)

c=float(input())
f=(c*9/5)+32
print(f)

n=int(input())
a,b=0,1
for i in range(n):
 print(a)
 a,b = b,a+b

a=input()
b=input()
a,b = b,a
print(a)
print(b)

a=int(input())
b=int(input())
c=int(input())
avg=(a+b+c)/3
print(avg)

n = input()
vowels ="aeiou"
count=0
for ch in n:
  if ch in vowels:
    print(ch)
    count+=1
print(count)

a=int(input())
b=int(input())
x=a
y=b
while b!=0:
  a,b = b,a%b

  gcd = a

  lcm=(x * y) // gcd
  print("GCD =",gcd)
  print("LCM =",lcm)

num = [3,17,29,7,65,92]
largest=max(num)
smallest=min(num)
print(largest)
print(smallest)

a=int(input())
b=int(input())
print("Add=",a+b)
print("Sub=",a-b)
print("Mul=",a*b)
print("div=",a%b)

a=int(input())
if a>0:
  print("positive")
elif a<0:
  print("negative")
else:
  print("zero")

x=int(input())
if x%4 == 0:
  print("leapyear")
else:
  print("not leapyear")

x=int(input())
if x%2 == 0:
  print("EVEN")
else:
  print("ODD")

s1=input()
s2=input()
if sorted (s1)==sorted (s2):
  print("Annagram")
else:
  print("Not Annagram")



for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="")
  print()

n=int(input())
for i in range(n):
  print (" "*i+"*"*(n-i))

n=int(input())
for i in range(1,n+1):
  print (" " * (n - i) + "* " * i)
for i in range(n-1,0,-1):
  print (" " * (n - i) + "* " * i)

n=int(input())
for i in range(1,n+1):
  print (" " * (n - i) + "* " * i)

s1=input()
s2=input()
if (s1==s2,s2==s1):
  print("Annagram")
else:
  print("Not Annagram")

a=[20,40,50,10,30]
largest = sorted(a,reverse = True)[:3]
print(largest)

import math
a=int(input())
if math.sqrt(a):
  print("power of 2")
else:
  print("not")

text = input()
s= text[3:13]
print(s)

s = input()

l = ""

for i in range(len(s)):
    cur = ""

    for j in range(i, len(s)):
        if s[j] not in cur:
            cur += s[j]
        else:
            break

    if len(cur) > len(l):
        l = cur

print(len(l))

s1 = input()
s2 = input()

count = 0
i = 0

try:
    while True:
        if s1[i] != s2[i]:
            count += 1
        i += 1

except:
    pass

if count == 1:
    print("yes")
else:
    print("no")

n = int(input())
x = list(map(int, input().split()))

for i in range(n):
  if x[i] == 0:
        d = x[i - 1] + 1
        print(d)
        break

#class & object
class student:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def display(self):
    print("Name:",self.name)
    print("Aga:",self.age)
obj = student("HEMS",3)
obj.display()

#inheritance
class father:
  def bike(self):
    print("father has bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj = son()
obj.bike()

#polymorphism(method overiding)
class Animal:
  def sound(self):
    print("animal make sound")
class Dog(Animal):
  def barks(self):
    print("dog barks")
obj = Dog()
obj.sound()

#abstraction
class bank:
  def __init__(self):
    self.__balance=5000
  def show_balance(self):
    print("balance",self.__balance)
obj = bank()
obj.show_balance()

#polymorphism(overloading)
class multiply:
  def product(self, a=None, b=None, c=None):
    if a and b and c:
      print("product=",a*b*c)
    elif a and b:
      print("product=",a*b)
    else :
      print("invalid input")
obj = multiply()
obj.product(2,3)
obj.product(2,3,4)

n=int(input())
S=str(n)
rev=s[::-1]
if(n>1):
  for i in range(2,n):
   if(n%i==0 and int(rev)%i==0):
    print("not prime")
    break
  else:
    print("prime")
else:
  print("not prime")

n=int(input())
a=0
for i in range(1,n+1):
  if(i%2==0):
    a=-i
  else:
    a=i
  print(a)

n=int(input())
s1=str(n)
r1=s1[::-1]
sq1=n**2
sq2=int(r1)**2
s2=str(sq2)
r2=s2[::-1]
if(sq1 == int(r2)):
 print("adam number")
else:
  print("not")

for _ in range(int(input())):
    n, k = map(int, input().split())
    a = list(input().split())
    count = 0
    for i in range(n):
        a[i] = int(a[i]) + k
        if (a[i] % 7 == 0):
            count += 1
    print(count)

for _ in range(int(input())):
    n,m = map(int,input().split())
    a = set(map(int,input().split()))
    b = set(map(int,input().split()))

    common = a.intersection(b)
    print(len(common))

k, n = map(int,input().split())
l = []
for j in range(k):
    l.append(input())
for s in range(n):
    t = input()
    if len(t) >= 47:
        print('Good')
        continue
    for j in l:
         if j in t:
             print('Good')
             break
    else:
          print('Bad')

student_name = input()
m1, m2, m3, m4 = map(int, input().split())
total = m1 + m2 + m3 + m4
avg = (m1 + m2 + m3 + m4)/4
highest = max(m1, m2, m3, m4)
print("Total", total)
print("Average", avg)
print("Highest Mark",highest )
if total < 350:
  print("status:Fail")
else:
  print("status:Pass")

Employee_name = input()
s1, s2, s3, s4, s5 = map(int, input().split())
avg = (s1 + s2 + s3 + s4 + s5)/4
highest = max(s1, s2, s3, s4, s5)
print("Average score", avg)
print("Best Score",highest)
count = 0
for i in s1,s2,s3,s4,s5:
 if i > 80:
   count+=1
print("Months Above 80:",count)

from os.path import isjunction
Attendance = [85, 70, 92, 65, 78, 88]
highest = max(Attendance)
lowest = min(Attendance)
print("Highest Attendance:",highest)
print("lowest Attendance:",lowest)
count=0
for i in Attendance:
  if Attendance >= 75%:
     count+=1
print("Months Above 80:",count)